#pragma once

#define OUTPUT_DEBUG 1

#if OUTPUT_DEBUG
#define OUTPUT_DEBUG_INTENSITY 0
#define OUTPUT_DEBUG_DISTANCE 0
#define OUTPUT_DEBUG_TIMESTAMP 0
#define OUTPUT_DEBUG_ZEROBLOCK 0
#endif